/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import model.ServiceCatalog;
import model.ServiceRecord;


/**
 *
 * @author fabio
 */
public class ManageVehiclesJPanel extends javax.swing.JPanel {
    private javax.swing.JPanel bottomPanel;
    private model.VehicleDirectory vehicleDirectory;
    private ArrayList<ServiceRecord> displayedRecords = new ArrayList<>();
    private ServiceCatalog serviceCatalog;




    /**
     * Creates new form ManageVehiclesJPanel
     */
    public ManageVehiclesJPanel(javax.swing.JPanel bottomPanel, ServiceCatalog serviceCatalog, model.VehicleDirectory vehicleDirectory) {
        initComponents();
        this.bottomPanel = bottomPanel;
        this.vehicleDirectory = vehicleDirectory;
        this.serviceCatalog = serviceCatalog;

        btnViewDetails.setEnabled(false);
        btnDeleteAccount.setEnabled(false);

        // single selection only
        jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        // enable buttons only when a row is selected
        jTable1.getSelectionModel().addListSelectionListener(e -> {
        boolean rowSelected = jTable1.getSelectedRow() >= 0;
        btnViewDetails.setEnabled(rowSelected);
        btnDeleteAccount.setEnabled(rowSelected);
        });

        // wire buttons
        btnBack.addActionListener(evt -> goBack());
        btnSearch.addActionListener(evt -> search());
        btnDeleteAccount.addActionListener(evt -> deleteSelected());
        btnViewDetails.addActionListener(evt -> viewDetails());

        // load initial table
        refreshTable(vehicleDirectory.getRecordList());
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnViewDetails = new javax.swing.JButton();
        btnDeleteAccount = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setText("Manage Vehicles");

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Owner ID", "Vechicle ID", "Service Opted", "Cost", "OwnerFirst", "OwnerLast", "Model", "Make", "Year"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnViewDetails.setText("View Details");

        btnDeleteAccount.setText("Delete Account");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 844, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(358, 358, 358)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDeleteAccount, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                            .addComponent(btnViewDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addGap(343, 343, 343))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(lblTitle)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch)
                    .addComponent(btnBack))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnViewDetails)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDeleteAccount)
                .addContainerGap(173, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        
        CardLayout cl = (CardLayout) bottomPanel.getLayout();
        cl.show(bottomPanel, "HOME");
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeleteAccount;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnViewDetails;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
private void refreshTable(ArrayList<ServiceRecord> records) {
    DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
    dtm.setRowCount(0);

    displayedRecords = records;

    for (ServiceRecord r : records) {
        Object[] row = new Object[9];
        row[0] = r.getOwner().getOwnerId();
        row[1] = r.getVehicle().getVehicleId();
        row[2] = r.getService().getServiceType();
        row[3] = r.getService().getCost();
        row[4] = r.getOwner().getFirstName();
        row[5] = r.getOwner().getLastName();
        row[6] = r.getVehicle().getModel();
        row[7] = r.getVehicle().getMake();
        row[8] = r.getVehicle().getYear();
        
        dtm.addRow(row);
    }

    btnViewDetails.setEnabled(false);
    btnDeleteAccount.setEnabled(false);
    jTable1.clearSelection();
}
private void goBack() {
    CardLayout cl = (CardLayout) bottomPanel.getLayout();
    cl.show(bottomPanel, "HOME");
}
private void search() {
    String query = txtSearch.getText().trim();

    if (query.isEmpty()) {
        refreshTable(vehicleDirectory.getRecordList());
        return;
    }

    // 1) If numeric -> search by Vehicle ID
    try {
        int vehicleId = Integer.parseInt(query);
        ServiceRecord record = vehicleDirectory.findByVehicleId(vehicleId);

        if (record == null) {
            // requirement says: if no match found, no action required
            return;
        }

        ArrayList<ServiceRecord> single = new ArrayList<>();
        single.add(record);
        refreshTable(single);
        return;

    } catch (NumberFormatException ex) {
        // not a number -> continue searching by text fields
    }

    // 2) Text search: model OR make OR owner first OR owner last (contains, case-insensitive)
    String q = query.toLowerCase();
    ArrayList<ServiceRecord> matches = new ArrayList<>();

    for (ServiceRecord r : vehicleDirectory.getRecordList()) {

    String model = r.getVehicle().getModel() == null ? "" : r.getVehicle().getModel().toLowerCase();
    String make  = r.getVehicle().getMake()  == null ? "" : r.getVehicle().getMake().toLowerCase();
    String first = r.getOwner().getFirstName() == null ? "" : r.getOwner().getFirstName().toLowerCase();
    String last  = r.getOwner().getLastName()  == null ? "" : r.getOwner().getLastName().toLowerCase();

    String serviceType = (r.getService() == null || r.getService().getServiceType() == null)
            ? ""
            : r.getService().getServiceType().toLowerCase();

    if (model.contains(q) || make.contains(q) || first.contains(q) || last.contains(q) || serviceType.contains(q)) {
        matches.add(r);
    }
}

if (matches.isEmpty()) {
    return; // no action required
}


    refreshTable(matches);
}
    private void deleteSelected() {
    int selectedRow = jTable1.getSelectedRow();
    if (selectedRow < 0) {
        JOptionPane.showMessageDialog(this, "Please select a row to delete.");
        return;
    }

    ServiceRecord record = displayedRecords.get(selectedRow);

    int choice = JOptionPane.showConfirmDialog(this,
            "Delete this record for Vehicle ID: " + record.getVehicle().getVehicleId() + "?",
            "Confirm Delete",
            JOptionPane.YES_NO_OPTION);

    if (choice != JOptionPane.YES_OPTION) return;

    vehicleDirectory.deleteRecord(record);
    JOptionPane.showMessageDialog(this, "Record deleted.");

    // refresh full table after delete
    refreshTable(vehicleDirectory.getRecordList());
    }
    
    private void viewDetails() {
    int selectedRow = jTable1.getSelectedRow();
    if (selectedRow < 0) {
        JOptionPane.showMessageDialog(this, "Please select a row to view.");
        return;
    }

    ServiceRecord record = displayedRecords.get(selectedRow);

    VehicleDetailsJPanel details =
            new VehicleDetailsJPanel(bottomPanel, vehicleDirectory, serviceCatalog, record);

    bottomPanel.add(details, "DETAILS");

    CardLayout cl = (CardLayout) bottomPanel.getLayout();
    cl.show(bottomPanel, "DETAILS");
}
    


    }
