/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

/**
 *
 * @author fabio
 */
public class RegisterOwnerVehicleJPanel extends javax.swing.JPanel {
    
    private javax.swing.JPanel bottomjPanel;
    private model.ServiceCatalog serviceCatalog;
    private model.VehicleDirectory vehicleDirectory;


    /**
     * Creates new form RegisterOwnerVehicleJPanel
     */
    public RegisterOwnerVehicleJPanel(javax.swing.JPanel bottomjPanel, model.ServiceCatalog serviceCatalog, model.VehicleDirectory vehicleDirectory) {
        initComponents();
        this.bottomjPanel = bottomjPanel;
        this.serviceCatalog = serviceCatalog;
        this.vehicleDirectory = vehicleDirectory;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
